import type { Metadata } from 'next'
import Header from '@/components/Header/Header'

export const metadata: Metadata = {
  title: 'My Cafe',
  description: 'Generated by create next app',
}

export default function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main>
      <Header />
      <main>{children}</main>
    </main>
  )
}
