import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.scss'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['300', '500', '700'],
})

export const metadata: Metadata = {
  title: 'My Cafe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  )
}
